# Generated by Django 4.2.7 on 2023-12-05 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='courses/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Monday', 'Mond'), ('Tuesday', 'Tusd'), ('Wednesday', 'Wdns'), ('Thursday', 'Thsd'), ('Friday', 'Frdy'), ('Saturday', 'Satd'), ('Sunday', 'Sudy')], max_length=10, unique=True)),
                ('order', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('attacments', models.ManyToManyField(related_name='lecture', to='courses.attachment')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='courses.day')),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('lectur', models.ManyToManyField(related_name='weeks', to='courses.lecture')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('info', models.TextField()),
                ('days', models.ManyToManyField(related_name='course', to='courses.day')),
                ('weeks', models.ManyToManyField(related_name='course', to='courses.week')),
            ],
        ),
    ]
