# Generated by Django 4.2.7 on 2023-11-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_weeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='week_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
