# Generated by Django 4.2.7 on 2023-12-05 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lecture_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='day',
        ),
    ]
