# Generated by Django 4.2.7 on 2023-12-18 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_lecture_options_remove_lecture_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='courses.day'),
        ),
    ]
