# Generated by Django 4.2.7 on 2023-12-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_lecture_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='days',
            field=models.ManyToManyField(blank=True, related_name='course', to='courses.day'),
        ),
        migrations.AlterField(
            model_name='course',
            name='weeks',
            field=models.ManyToManyField(blank=True, related_name='course', to='courses.week'),
        ),
    ]
